name: CSTGAM_RGB2THERMAL
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch=1.8.1
- scipy
- pip
- pip:
  - dominate==2.6.0
  - torchvision==0.9.1
  - Pillow==8.0.1
  - numpy==1.19.4
  - visdom==0.1.8
  - wandb==0.12.18
  - opencv-python==4.4.0.46
  - ipython==7.19.0
  - timm==0.4.12
  - tqdm==4.62.2
  


